# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-04 18:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('end_datetime', models.DateTimeField(verbose_name='Finished')),
                ('start_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Started')),
                ('reported', models.BooleanField(default=False, verbose_name='Reported')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Category', verbose_name='Category')),
                ('id_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.RemoveField(
            model_name='commit',
            name='category',
        ),
        migrations.RemoveField(
            model_name='commit',
            name='id_user',
        ),
        migrations.RemoveField(
            model_name='commit',
            name='repository',
        ),
        migrations.DeleteModel(
            name='Commit',
        ),
    ]
